In [1]:
import clustersimpy as cp
import numpy as np

In [2]:
## This Data Has been aclaucled as PC not AU. oops!!
Sim_Data = cp.data('PLANET_TEST_N2_RAU_EPS40029')

In [3]:
Sim_Data.read()

N =  2
time 300000.0
units:  1.9884699e+33 3.0856775e+18 31556952.0
mass array [5.9724e-06 1.0000e+00]
PLANET_TEST_N2_RAU_EPS40029  Data Read successfully!


In [9]:
X = Sim_Data.x
Y = Sim_Data.y
Z = Sim_Data.z
#print(X)
R_vec = np.array((X,Y,Z)).T
#print(R_vec)

VX = Sim_Data.vx
VY = Sim_Data.vy
VZ = Sim_Data.vz
#print(X)
V_vec = np.array((VX,VY,VZ)).T

Mass = Sim_Data.mass
print(Mass) #Mp,Mstar
print(R_vec,V_vec)
print(R_vec.shape,V_vec.shape)
print(np.dot(R_vec,V_vec))

[5.9724e-06 1.0000e+00]
[[1.00000000e+00 8.95403675e+09 0.00000000e+00]
 [2.69951396e-19 2.69951692e-19 0.00000000e+00]] [[-1.50666062e-19  2.98467892e+04  0.00000000e+00]
 [ 8.99837987e-25  8.99838976e-25  0.00000000e+00]]
(2, 3) (2, 3)


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [11]:
Calc = cp.measure([Mass[1],Mass[0],(R_vec[0]-R_vec[1]),(V_vec[0] - V_vec[1])])
A = Calc.calculate_a()
print(A)
E = Calc.calculate_e(A)
print(E)
Calc.graph('2D')
Calc.graph('3D')

1.0000000002233627
8954036747.846657


TypeError: graph() missing 2 required positional arguments: 'a' and 'e'